parameters:
    image_resizer.resizer.class: Ant\ImageResizeBundle\Image\Resizer
    image_resizer.image_loader.gaufrette.class: Ant\ImageResizeBundle\Image\ImageLoader\ImageGaufretteLoader
    image_resizer.image_loader.file.class: Ant\ImageResizeBundle\Image\ImageLoader\ImageGaufretteFile
    image_resizer.resize_proccessor.proportional_resize_proccessor.class: Ant\ImageResizeBundle\Image\ResizeProccessor\ProportionaResizeProccessor

services:
    image_resizer.resizer:
        class: %image_resizer.resizer.class%
        arguments: [image_resizer.image_loader.type, {proportional: @image_resizer.resize_proccessor.proportional_resize_proccessor}]
    image_resizer.image_loader.gaufrette:
        class: %image_resizer.image_loader.gaufrette.class%
        arguments: [@image_resizer.imagine, image_resizer.image_loader.gaufrette_filesystem]
    image_resizer.image_loader.file:
        class: %image_resizer.image_loader.file.class%
        arguments: [@image_resizer.imagine]
    image_resizer.resize_proccessor.proportional_resize_proccessor:
        class : %image_resizer.resize_proccessor.proportional_resize_proccessor.class%
    image_resizer.imagine:
        class: %image.image_resizer.class%